src/antwoorden_cms/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from ratelimit.decorators import ratelimit
from two_factor.urls import urlpatterns as tf_urls

from antwoorden_cms.revproxy.view import RevProxyView

from .accounts.admin import CustomAdminSiteOTPRequired
from .accounts.views import GitLabTokenValidView, GitLabTokenView
from .config.views import WidgetStylingView
from .registration_urls import urlpatterns as registration_urls

handler500 = "antwoorden_cms.utils.views.server_error"
admin.site.site_header = "antwoorden_cms admin"
admin.site.site_title = "antwoorden_cms admin"
admin.site.index_title = "Welcome to the antwoorden_cms admin"

admin.site.__class__ = CustomAdminSiteOTPRequired

urlpatterns = [
    path("", include(tf_urls)),
    path("gitlab-token/", GitLabTokenView.as_view(), name="gitlab_token"),
    path(
        "gitlab-token/check_valid",
        GitLabTokenValidView.as_view(),
        name="gitlab_token_check_valid",
    ),
    path(
        "password_change/",
        ratelimit(key="user", method="POST", rate="5/h", block=True)(
            auth_views.PasswordChangeView.as_view()
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path("admin/hijack/", include("hijack.urls")),
    path("admin/", admin.site.urls),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Simply show the master template.
    # path("", RedirectView.as_view(url="/api/redoc/"), name="home"),
    path("api/", include("antwoorden_cms.utters.api.urls", namespace="antwoorden_cms")),
    path("", include("antwoorden_cms.utters.urls", namespace="gemeentes")),
    path("config/", include("antwoorden_cms.config.urls", namespace="config")),
    path("overview/", include("antwoorden_cms.dialogs.urls", namespace="dialogs")),
    path(
        "statistics/", include("antwoorden_cms.statistics.urls", namespace="statistics")
    ),
    path("accounts/", include(registration_urls)),
    path("i18n/", include("django.conf.urls.i18n")),
    # For backward compatibility
    path(
        "<slug:gemeente_slug>/_styling",
        WidgetStylingView.as_view(content_type="text/css"),
        name="widget_styling",
    ),
    path(
        "services/<str:host_and_port>/",
        RevProxyView.as_view(),
        name="revproxy",
    ),
    path(
        "services/<str:host_and_port>/<path:rest>",
        RevProxyView.as_view(),
        name="revproxy",
    ),
]

# NOTE: The staticfiles_urlpatterns also discovers static files (ie. no need to run collectstatic). Both the static
# folder and the media folder are only served via Django if DEBUG = True.
urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG and apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

src/antwoorden_cms/utters/api/urls.py
from django.conf import settings
from django.urls import path, re_path

from ..apps import AppConfig
from .api import schema_view
from .views import (
    DomainMetadataView,
    OrganisationDomainViewSet,
    OrganisationStorySettingsViewSet,
    OrganisationViewSet,
    PageMetadataView,
    ScrapyWebhookView,
    UtterResponseViewSet,
)

app_name = AppConfig.__name__


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path(
        "organisations/",
        OrganisationViewSet.as_view(
            {
                "get": "list",
            },
        ),
        name="organisation_list",
    ),
    path(
        "organisations/<slug:organisation_slug>/",
        OrganisationViewSet.as_view(
            {
                "get": "retrieve",
            },
        ),
        name="organisation_detail",
    ),
    path(
        "organisations/domains/<slug:organisation_slug>/",
        OrganisationDomainViewSet.as_view(
            {
                "get": "retrieve",
            },
        ),
        name="organisation_domains",
    ),
    path(
        "<slug:gemeente>/utters/<slug:utter_name>/",
        UtterResponseViewSet.as_view({"get": "retrieve"}),
        name="utters",
    ),
    path(
        "<slug:organisation>/stories/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "get": "list",
            }
        ),
        name="story_settings_list",
    ),
    path(
        "<slug:organisation>/stories/_bulk_create_or_update/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "post": "bulk_create_or_update",
            }
        ),
        name="story_settings_bulk_endpoint",
    ),
    path(
        "<slug:organisation>/stories/<slug:story_id>/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "get": "retrieve",
                "post": "create",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="story_settings",
    ),
    path(
        "page-metadata",
        PageMetadataView.as_view({"post": "create"}),
        name="page_metadata",
    ),
    path(
        "domain-metadata",
        DomainMetadataView.as_view({"get": "retrieve"}),
        name="domain_metadata",
    ),
]

if settings.ENABLE_SCRAPY_ENDPOINT:
    urlpatterns.append(
        path(
            "scrapy-webhook",
            ScrapyWebhookView.as_view(),
            name="scrapy_webhook",
        ),
    )

src/antwoorden_cms/utters/urls.py
from django.urls import path

from .apps import AppConfig
from .views import (
    DynamicHyperlinkListView,
    DynamicRequiredHyperlinkListView,
    GemeenteView,
    HomePageView,
    HyperlinkCreateView,
    HyperlinkDeleteView,
    HyperlinkDetailView,
    HyperlinkEditableListView,
    HyperlinkListView,
    HyperlinkUpdateView,
    StoriesListView,
    UtterResponseChangeListView,
    UtterResponseCreatedListView,
    UtterResponseCreateView,
    UtterResponseDeleteView,
    UtterResponseDetailView,
    UtterResponseListView,
    UtterResponseRequiredEditableListView,
    UtterResponseUpdateView,
)

app_name = AppConfig.__name__

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    # Lists of yet to be edited responses
    # path('<slug:gemeente_slug>/antwoorden/editable/', UtterResponseEditableListView.as_view(), name='antwoord_list_editable'),
    path(
        "<slug:gemeente_slug>/antwoorden/editable/required",
        UtterResponseRequiredEditableListView.as_view(),
        name="antwoord_list_editable_required",
    ),
    # Municipality specific responses
    path("<slug:gemeente_slug>/", GemeenteView.as_view(), name="gemeente_detail"),
    path(
        "<slug:gemeente_slug>/antwoorden/",
        UtterResponseListView.as_view(),
        name="antwoord_list",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/create/",
        UtterResponseCreateView.as_view(),
        name="antwoord_create",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/",
        UtterResponseDetailView.as_view(),
        name="antwoord_read",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/update",
        UtterResponseUpdateView.as_view(),
        name="antwoord_update",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/delete/",
        UtterResponseDeleteView.as_view(),
        name="antwoord_delete",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/changed",
        UtterResponseChangeListView.as_view(),
        name="antwoord_changed_overview",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/created",
        UtterResponseCreatedListView.as_view(),
        name="antwoord_created_overview",
    ),
    path(
        "<slug:gemeente_slug>/stories/<str:category>",
        StoriesListView.as_view(),
        name="stories_list",
    ),
    # Variables pages
    path(
        "<slug:gemeente_slug>/hyperlinks/",
        HyperlinkListView.as_view(),
        name="hyperlink_list",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/editable/",
        HyperlinkEditableListView.as_view(),
        name="hyperlink_list_editable",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/create",
        HyperlinkCreateView.as_view(),
        name="hyperlink_create",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/",
        HyperlinkDetailView.as_view(),
        name="hyperlink_read",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/update",
        HyperlinkUpdateView.as_view(),
        name="hyperlink_update",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/delete/",
        HyperlinkDeleteView.as_view(),
        name="hyperlink_delete",
    ),
    # Dynamic hyperlinks
    path(
        "<slug:gemeente_slug>/dynamic-hyperlinks/",
        DynamicHyperlinkListView.as_view(),
        name="dynamic_hyperlink_list",
    ),
    path(
        "<slug:gemeente_slug>/dynamic-required-hyperlinks/",
        DynamicRequiredHyperlinkListView.as_view(),
        name="dynamic_required_hyperlink_list",
    ),
]

src/antwoorden_cms/utters/forms.py
from copy import copy

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Gemeente, Hyperlink, SiteConfiguration, UtterResponse


class UtterResponseForm(forms.ModelForm):
    class Meta:
        model = UtterResponse
        fields = ("response",)
        labels = {"response": _("Antwoord")}

    def __init__(self, *args, **kwargs):
        self.gemeente = kwargs.pop("gemeente", "")
        self.is_staged = kwargs.pop("is_staged", "")
        super().__init__(*args, **kwargs)

        self.fields["response"].label = f"Antwoord Gem {self.gemeente}"

        # The help_text from the utter metadata will be used instead
        self.fields["response"].help_text = ""

    def clean(self):
        # Validate that utter does not exist yet for municipality
        if self.gemeente and self.initial.get("utter"):
            if UtterResponse.objects.filter(
                gemeente__name=self.gemeente,
                utter=self.initial["utter"],
                is_staged=self.is_staged,
            ).exists():
                raise ValidationError(_("Dit antwoord bestaat al voor deze gemeente"))


class HyperlinkForm(forms.ModelForm):
    class Meta:
        model = Hyperlink
        fields = (
            "name",
            "label",
            "url",
            "title",
        )
        labels = {
            "name": _("Machinenaam"),
        }

    def __init__(self, *args, **kwargs):
        required = kwargs.pop("required", [])
        self.gemeente = kwargs.pop("gemeente", "")
        self.is_staged = kwargs.pop("is_staged", "")

        super().__init__(*args, **kwargs)

        # In case of creating a custom Hyperlink (not used in default utters)
        if not self.instance.id and not self.initial.get("name"):
            return

        # Make `name` not editable when creating a predefined Hyperlink
        if self.initial.get("name"):
            self.fields["name"].disabled = True

        # Do not allow editing of name
        if self.instance.id:
            self.fields.pop("name")

        fields = copy(self.fields)

        site_config = SiteConfiguration.get_solo()

        for field in fields:
            if field == "label":
                continue

            # Only remove fields if specified in site configuration
            if field != "name" and field not in required:
                if site_config.hyperlinks_show_only_used_attributes:
                    self.fields.pop(field)
            else:
                self.fields[field].required = True

    def clean(self):
        data = self.cleaned_data

        # Validate that hyperlink does not exist yet for municipality
        if self.gemeente and not self.instance.pk:
            if Hyperlink.objects.filter(
                gemeente=self.gemeente,
                name=data.get("name", self.initial["name"]),
                is_staged=self.is_staged,
            ).exists():
                raise ValidationError(_("Deze variabele bestaat al voor deze gemeente"))


class GemeenteAdminForm(forms.ModelForm):
    class Meta:
        model = Gemeente
        fields = "__all__"
        widgets = {
            "main_widget_color": forms.widgets.TextInput(attrs={"type": "color"}),
        }


class HyperlinksImportForm(forms.Form):
    import_file = forms.FileField(
        label=_("bestand"),
        required=True,
        help_text=_("Het YAML bestand met de hyperlinks."),
    )

src/antwoorden_cms/utters/templates/utters/includes/antwoord_accept.html
{% load i18n %}
<button class="btn btn-success float-right mt-2 accept-button"
    data-target-url="{% url 'gemeentes:antwoord_update' gemeente_slug=gemeente.slug antwoord_pk=antwoord.pk %}"
    data-response="{{response}}">
    <i class="cui-check"></i> {% trans "Lokale variant klopt nog" %}
</button>

src/antwoorden_cms/utters/templates/utters/includes/antwoord_create.html
{% load i18n %}
{% trans "Lokale variant aanmaken" as default_label %}
<a href="{% url "gemeentes:antwoord_create" gemeente_slug=gemeente.slug %}?utter_name={{ utter_name }}"
    class="{{custom_classes|default:"btn btn-success float-right ml-2"}}">
    <i class="{{icon_class|default:"cui-library-add"}}"></i> {{label|default:default_label}}
</a>

src/antwoorden_cms/utters/templates/utters/includes/antwoord_delete.html
{% load i18n %}
{% trans "Terug naar landelijk standaardantwoord (verwijder lokale variant)" as default_title %}
<a href="{% url 'gemeentes:antwoord_delete' gemeente_slug=gemeente.slug antwoord_pk=antwoord.pk %}"
    data-toggle="tooltip" title="{{title|default:default_title}}"
    class="btn btn-danger float-right ml-2 delete-button delete-response {{extra_classes}}">
    <i class="cui-trash"></i> {{label}}
</a>

src/antwoorden_cms/utters/templates/utters/includes/antwoord_update.html
{% load i18n %}
{% trans "Lokale variant aanpassen" as default_label %}
<a href="{% url 'gemeentes:antwoord_update' gemeente_slug=gemeente.slug antwoord_pk=antwoord.pk %}"
    class="btn btn-primary float-right ml-2">
    <i class="cui-pencil"></i> {{label|default:default_label}}
</a>

src/antwoorden_cms/utters/templates/utters/includes/auditlog.html
<div class="auditlog">
    <b>Antwoord aangepast op {{utterresponse.modified_on}}{% if utterresponse.history.latest %} door {{utterresponse.history.latest.actor.first_name}} {{utterresponse.history.latest.actor.last_name}}{% endif %}</b>
</div>

src/antwoorden_cms/utters/templates/utters/includes/hyperlink_metadata.html
{% load i18n markdownify %}

{% if metadata %}
    <p id="hint_id_response" class="form-text mb-3"><i>{{ metadata.help_text|markdownify }}</i></p>
    <table class="table table-hover hyperlink-metadata" id="hyperlink-metadata">
        <tr>
            <td><b>{% trans "Naam" %}</b></td>
            <td>{{ metadata.verbose_name }}</td>
        </tr>
        <tr>
            <td><b>{% trans "Categorie" %}</b></td>
            <td>{{ metadata.category }}</td>
        </tr>
    </table>
{% endif %}

src/antwoorden_cms/utters/templates/utters/includes/toggle_prod_data.html
{% load i18n %}
<button class="btn btn-warning toggle-prod-data float-right {{extra_classes}}" data-target="#row-{{utter_name}}" data-untoggle-text="{% trans 'Verberg live antwoord' %}">
    {% comment %} <i class="cui-toggle-off"></i> {% endcomment %}
    {% trans "Toon live antwoord" %}
</button>

src/antwoorden_cms/utters/templates/utters/includes/utter_metadata.html
{% load i18n %}

{% if utter_metadata %}
    <table class="table table-hover utter-metadata" id="utter-metadata">
    {% if utter_metadata.questions %}
        <tr>
            <td><b>{% trans "Klantvraag/vragen" %}</b></td>
            <td>
                <ul class="utter-metadata__list">
                    {% for question in utter_metadata.questions %}
                        <li>{{ question }}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endif %}
    {% if utter_metadata.examples %}
        <tr>
            <td><b>{% trans "Voorbeeld antwoord(en) Gem" %}</b></td>
            <td>
                <ul class="utter-metadata__list">
                    {% for example in utter_metadata.examples %}
                        <li>{{ example }}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endif %}
    {% if utter_metadata.related %}
        <tr>
            <td><b>{% trans "Vergelijkbare antwoorden" %}</b></td>
            <td>
                <ul class="utter-metadata__list">
                    {% for related in utter_metadata.related %}
                        <li>{{ related }}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endif %}
    </table>
{% endif %}