src/antwoorden_cms/statistics/urls.py
from django.urls import path

from .apps import AppConfig
from .views import (
    DynamicStatisticsView,
    GraphScriptView,
    StatisticsDashboardView,
    StatisticsExportView,
)

app_name = AppConfig.__name__

urlpatterns = [
    # New statistics
    path(
        "<slug:gemeente_slug>/dashboard/",
        StatisticsDashboardView.as_view(),
        name="statistics_dashboard",
    ),
    path(
        "<slug:gemeente_slug>/<slug:graph_slug>/",
        DynamicStatisticsView.as_view(),
        name="dynamic_statistics",
    ),
    path(
        "<slug:gemeente_slug>/_scripts/<slug:graph_slug>/",
        GraphScriptView.as_view(),
        name="graph_scripts",
    ),
    path(
        "<slug:gemeente_slug>/export",
        StatisticsExportView.as_view(),
        name="statistics_export",
    ),
]

src/antwoorden_cms/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from ratelimit.decorators import ratelimit
from two_factor.urls import urlpatterns as tf_urls

from antwoorden_cms.revproxy.view import RevProxyView

from .accounts.admin import CustomAdminSiteOTPRequired
from .accounts.views import GitLabTokenValidView, GitLabTokenView
from .config.views import WidgetStylingView
from .registration_urls import urlpatterns as registration_urls

handler500 = "antwoorden_cms.utils.views.server_error"
admin.site.site_header = "antwoorden_cms admin"
admin.site.site_title = "antwoorden_cms admin"
admin.site.index_title = "Welcome to the antwoorden_cms admin"

admin.site.__class__ = CustomAdminSiteOTPRequired

urlpatterns = [
    path("", include(tf_urls)),
    path("gitlab-token/", GitLabTokenView.as_view(), name="gitlab_token"),
    path(
        "gitlab-token/check_valid",
        GitLabTokenValidView.as_view(),
        name="gitlab_token_check_valid",
    ),
    path(
        "password_change/",
        ratelimit(key="user", method="POST", rate="5/h", block=True)(
            auth_views.PasswordChangeView.as_view()
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path("admin/hijack/", include("hijack.urls")),
    path("admin/", admin.site.urls),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Simply show the master template.
    # path("", RedirectView.as_view(url="/api/redoc/"), name="home"),
    path("api/", include("antwoorden_cms.utters.api.urls", namespace="antwoorden_cms")),
    path("", include("antwoorden_cms.utters.urls", namespace="gemeentes")),
    path("config/", include("antwoorden_cms.config.urls", namespace="config")),
    path("overview/", include("antwoorden_cms.dialogs.urls", namespace="dialogs")),
    path(
        "statistics/", include("antwoorden_cms.statistics.urls", namespace="statistics")
    ),
    path("accounts/", include(registration_urls)),
    path("i18n/", include("django.conf.urls.i18n")),
    # For backward compatibility
    path(
        "<slug:gemeente_slug>/_styling",
        WidgetStylingView.as_view(content_type="text/css"),
        name="widget_styling",
    ),
    path(
        "services/<str:host_and_port>/",
        RevProxyView.as_view(),
        name="revproxy",
    ),
    path(
        "services/<str:host_and_port>/<path:rest>",
        RevProxyView.as_view(),
        name="revproxy",
    ),
]

# NOTE: The staticfiles_urlpatterns also discovers static files (ie. no need to run collectstatic). Both the static
# folder and the media folder are only served via Django if DEBUG = True.
urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG and apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

src/antwoorden_cms/statistics/models.py
import logging

from django.db import models
from django.utils.translation import gettext_lazy as _

from ordered_model.models import OrderedModel

from .constants import PeriodUnits

logger = logging.getLogger(__name__)


class Graph(OrderedModel):
    slug = models.SlugField(
        verbose_name=_("URL-deel"),
        help_text=_("Pad waarop de grafiek bereikbaar is"),
        unique=True,
    )
    graph_duration = models.IntegerField(
        verbose_name=_("Periode"),
        help_text=_("Geeft aan tot hoe ver terug de data in de grafiek gaat."),
        null=True,
        blank=True,
    )
    graph_duration_default_unit = models.CharField(
        verbose_name=_("Standaard periode eenheid"),
        help_text=_("Geeft aan tot hoe ver terug de data in de grafiek gaat."),
        null=True,
        blank=True,
        max_length=52,
        choices=PeriodUnits.choices,
    )
    round_duration = models.BooleanField(
        verbose_name=_("Rond periode af"),
        default=True,
        help_text=_(
            "Indien aangevinkt wordt de periode afgerond, zodat deze altijd begint bij het begin van de kleinste eenheid."
        ),
    )
    title = models.CharField(
        verbose_name=_("Korte titel"),
        max_length=512,
        help_text=_("Titel die getoond wordt boven de grafiek"),
    )
    verbose_title = models.CharField(
        verbose_name=_("Titel"),
        max_length=1024,
        help_text=_("Titel die op de tegel getoond wordt"),
    )
    code = models.TextField(
        verbose_name=_("Javascript code"),
        help_text=_("Javascript code die uitgevoerd wordt om de grafiek op te bouwen"),
    )
    description = models.TextField(
        verbose_name=_("Omschrijving"),
        blank=True,
        help_text=_("Omschrijving die getoond wordt bij de grafiek"),
    )
    extra_query_params = models.JSONField(
        verbose_name=_("Extra query parameters"),
        default=dict,
        help_text=_(
            "Extra query parameters die gebruikt worden bij de request naar de statistieken API"
        ),
    )

    def __str__(self):
        return self.title

src/antwoorden_cms/statistics/views.py
import logging
import math
from datetime import datetime

from django.http import StreamingHttpResponse
from django.utils import timezone
from django.views.generic import DetailView, View

from dateutil.relativedelta import relativedelta
from two_factor.views import OTPRequiredMixin

from antwoorden_cms.statistics.statistics_client import StatisticsClient

from ..utters.mixins import ObjectPermissionMixin
from ..utters.models import Gemeente
from .models import Graph

logger = logging.getLogger(__name__)


class GraphScriptView(DetailView):
    model = Graph
    slug_url_kwarg = "graph_slug"
    slug_field = "slug"
    template_name = "graph_script.html"
    content_type = "text/javascript"


class DynamicStatisticsView(OTPRequiredMixin, ObjectPermissionMixin, DetailView):
    permission_required = "utters.statistics_read"
    template_name = "dynamic_statistics.html"
    model = Graph
    slug_url_kwarg = "graph_slug"
    slug_field = "slug"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        unit = self.request.GET.get("unit", self.object.graph_duration_default_unit)

        now = timezone.now().astimezone(timezone.pytz.timezone("Europe/Amsterdam"))
        # Ensure the date is properly rounded
        if unit == "days":
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        if unit == "weeks":
            days_since_start_of_week = now.weekday()
            start_of_week = now - relativedelta(days=days_since_start_of_week)
            now = start_of_week.replace(hour=0, minute=0, second=0, microsecond=0)
        if unit == "months":
            now = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        if unit == "years":
            now = now.replace(month=1, day=1, hour=0, minute=0, second=0, microsecond=0)

        offset = self.request.GET.get("offset", None)
        try:
            offset = int(offset)
        except TypeError:
            offset = 0

        date = self.request.GET.get("date", None)
        if date:
            selected_date = datetime.strptime(date, "%Y-%m-%d").date()
            difference = (selected_date - now.date()).days

            offset = difference / self.object.graph_duration
            if offset.is_integer():
                offset += 1
            else:
                offset = math.ceil(offset)

        # Round the begin_date to the beginning of the smallest unit
        duration = relativedelta(**{unit: self.object.graph_duration})

        begin_date = now - (abs(offset) + 1) * duration
        # Ensure the proper timezone with/without DST is used
        begin_date = begin_date.astimezone(
            timezone.pytz.timezone("Europe/Amsterdam")
        ).replace(
            year=begin_date.year,
            month=begin_date.month,
            day=begin_date.day,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
        )
        end_date = now - (abs(offset) * duration)
        # Ensure the proper timezone with/without DST is used
        end_date = end_date.astimezone(
            timezone.pytz.timezone("Europe/Amsterdam")
        ).replace(
            year=end_date.year,
            month=end_date.month,
            day=end_date.day,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
        )

        query_params = {
            **self.object.extra_query_params,
            "start__gte": begin_date,
            "start__lt": end_date,
            "ordering": "start",
        }

        if (
            unit != self.object.graph_duration_default_unit
            and self.object.graph_duration != 1
        ):
            if unit == "days":
                query_params.update({"groupByX": "date"})
            if unit == "weeks":
                query_params.update({"groupByX": "iso_weekdate_year,week"})
            if unit == "months":
                query_params.update({"groupByX": "year,month"})
            if unit == "years":
                query_params.update({"groupByX": "year"})

        response = StatisticsClient.fetch_aggregated_statistics(
            organisation_id=self.get_permission_object().name, params=query_params
        )
        context["statistics"] = response
        context["statistics"]["params"] = query_params
        context["offset"] = offset
        context["duration"] = self.object.graph_duration
        context["unit"] = unit
        context["begin_date"] = begin_date
        context["end_date"] = end_date

        return context


class StatisticsDashboardView(DetailView):
    model = Gemeente
    slug_url_kwarg = "gemeente_slug"
    template_name = "statistics_dashboard.html"
    permission_required = "utters.gemeente_read"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["graph_definitions"] = Graph.objects.all()
        return context


def cast_nullboolean_to_int(boolean):
    if boolean is None:
        return boolean

    return int(boolean)


class StatisticsExportView(View):
    def get(self, request, *args, **kwargs):
        gemeente = Gemeente.objects.get(slug=self.kwargs["gemeente_slug"])

        extra_params = {}
        if "timestamp__gte" in self.request.GET:
            extra_params["start__gte"] = self.request.GET.get("timestamp__gte")
        if "timestamp__lt" in self.request.GET:
            extra_params["start__lt"] = self.request.GET.get("timestamp__lt")

        params = {
            "ordering": "start",
        }

        params.update(extra_params)

        response = StatisticsClient.fetch_statistics(
            organisation_id=gemeente.name,
            session_id=None,
            params=params,
            type_="csv",
            stream=True,
        )

        response = StreamingHttpResponse(
            streaming_content=response.iter_content(chunk_size=64 * 1024),
            content_type="text/csv",
        )
        # Needed for proper filename encoding when using Safari as browser
        response["Content-Disposition"] = "attachment; filename=export.csv"
        return response

src/antwoorden_cms/statistics/templates/dynamic_statistics.html
{% extends "master.html" %}
{% load static i18n django_bootstrap_breadcrumbs markdownify %}

{% block title %}Antwoorden CMS | {{object.title}} {{current_gemeente.name}}{% endblock %}

{% block breadcrumb %}
    {% breadcrumb current_gemeente.name 'gemeentes:gemeente_detail' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Statistieken" 'statistics:statistics_dashboard' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb object.title 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}
    {% render_breadcrumbs 'components/breadcrumbs/breadcrumbs.html' %}
{% endblock %}

{% block body-class %}{% trans "Statistieken" %}{% endblock %}

{% block content %}
<div id="ui-view">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{object.verbose_title}} ({% trans "Gemeente" %} {{current_gemeente.name}}) tussen <b>{{ begin_date|date }}</b> en <b>{{ end_date|date }}</b>

                    <div class="float-right">
                        {% if unit == "days" %}
                            Datum: <input id="graph-datepicker" max="" type="date" data-url="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?unit=days" />
                        {% endif %}
                        <a class={% if unit == "years" %}"btn btn-primary"{% else %}"btn"{% endif %} href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?unit=years">
                            {% if duration > 1 %}Jaren{% else %}Jaar{% endif %}
                        </a>
                        <a class={% if unit == "months" %}"btn btn-primary"{% else %}"btn"{% endif %} href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?unit=months">
                            Maand{{duration|pluralize:"en"}}
                        </a>
                        <a class={% if unit == "weeks" %}"btn btn-primary"{% else %}"btn"{% endif %} href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?unit=weeks">
                            {% if duration > 1 %}Weken{% else %}Week{% endif %}
                        </a>
                        <a class={% if unit == "days" %}"btn btn-primary"{% else %}"btn"{% endif %} href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?unit=days">
                            Dag{{duration|pluralize:"en"}}
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="graph-container">
                        <div class="graph-navigation-left">
                            <a class="graph-navigation-link" href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?offset={{offset|add:-1}}&unit={{unit}}" />&#x25C4;</a>
                        </div>

                        <canvas id="myChart"></canvas>

                        {% if offset < 0 %}
                        <div class="graph-navigation-right">
                            <a class="graph-navigation-link"  href="{% url 'statistics:dynamic_statistics' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}?offset={{offset|add:1}}&unit={{unit}}" />&#x25BA;</a>
                        </div>
                        {% endif %}
                    </div>

                    {{object.description|markdownify}}
                </div>
            </div>
        </div>
    </div>
</div>

{{statistics|json_script:"statistics"}}

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.js" integrity="sha384-9R67RXFKxJXd/+QmlkaEyOhcfa0gbkwDQ4LUr1RvuTZp9u4VDylkCdExAVOi6zqz" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@sgratzl/chartjs-chart-boxplot@4.2.0/build/index.umd.min.js" integrity="sha384-5KhEyLSfbtWz1KzxlMgNbBcgVlEr2K87DYqL9z4YK5m9XhTe9N7EJYrOQFgnISzZ" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0" integrity="sha384-M00GJNq2IplZCB3+JOJEl2H0un45ODvqJSSnIc4DvG8gPn8RX5ToITFXcv3AvOx5" crossorigin="anonymous"></script>
<script src="{% url 'statistics:graph_scripts' gemeente_slug=current_gemeente.slug graph_slug=object.slug %}"></script>

{% endblock %}

src/antwoorden_cms/statistics/templates/graph_script.html
{{object.code|safe}}

src/antwoorden_cms/statistics/templates/intent_detail_statistics.html
{% extends "master.html" %}
{% load static i18n django_bootstrap_breadcrumbs %}

{% block title %}Antwoorden CMS | {% trans "Statistieken voor gemeente" %} {{current_gemeente.name}}{% endblock %}

{% block body-class %}{% trans "Statistieken" %}{% endblock %}

{% block breadcrumb %}
    {% breadcrumb current_gemeente.name 'gemeentes:gemeente_detail' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Statistieken" 'statistics:legacy_statistics_dashboard' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Meestvoorkomende intents" 'statistics:popular_intents_stats' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Intent statistieken detail" 'gemeentes:antwoorden_list' gemeente_slug=current_gemeente.slug %}
    {% render_breadcrumbs 'components/breadcrumbs/breadcrumbs.html' %}
{% endblock %}

{% block content %}
<div id="ui-view">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {% trans "Intent" %} {{intent_name}} ({% trans "Gemeente" %} {{current_gemeente.name}})
                </div>
                <div class="card-body">
                    <div style="position: relative">
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{{stats|json_script:"intentDetailStats"}}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js" integrity="sha384-0saKbDOWtYAw5aP4czPUm6ByY5JojfQ9Co6wDgkuM7Zn+anp+4Rj92oGK8cbV91S" crossorigin="anonymous"></script>

{% endblock %}

src/antwoorden_cms/statistics/templates/product_statistics.html
{% extends "master.html" %}
{% load static i18n django_bootstrap_breadcrumbs %}

{% block title %}Antwoorden CMS | {% trans "Statistieken voor gemeente" %} {{current_gemeente.name}}{% endblock %}

{% block body-class %}{% trans "Statistieken" %}{% endblock %}

{% block breadcrumb %}
    {% breadcrumb current_gemeente.name 'gemeentes:gemeente_detail' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Statistieken" 'statistics:legacy_statistics_dashboard' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Product statistieken" 'gemeentes:antwoorden_list' gemeente_slug=current_gemeente.slug %}
    {% render_breadcrumbs 'components/breadcrumbs/breadcrumbs.html' %}
{% endblock %}

{% block content %}
<div id="ui-view">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {% trans "Wat inwoners vragen, en wat Gem daarvan begrijpt" %} ({% trans "Gemeente" %} {{current_gemeente.name}})
                </div>
                <div class="card-body">
                    {% for month_data in stats %}
                        {% if month_data.1 %}
                        <h2>{{month_data.0}}</h2>
                        <div>
                            <canvas id="myChart-{{forloop.counter}}"></canvas>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{{stats|json_script:"productStats"}}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js" integrity="sha384-0saKbDOWtYAw5aP4czPUm6ByY5JojfQ9Co6wDgkuM7Zn+anp+4Rj92oGK8cbV91S" crossorigin="anonymous"></script>

{% endblock %}

src/antwoorden_cms/statistics/templates/statistics_dashboard.html
{% extends "master.html" %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}
{% load static %}

{% block title %}Antwoorden CMS | {% trans "Gemeente" %} {{object.name}}{% endblock %}

{% block breadcrumb %}
    {% breadcrumb current_gemeente.name 'gemeentes:gemeente_detail' gemeente_slug=current_gemeente.slug %}
    {% breadcrumb "Statistieken" 'statistics:statistics_dashboard' gemeente_slug=current_gemeente.slug %}
    {% render_breadcrumbs 'components/breadcrumbs/breadcrumbs.html' %}
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
<div id="ui-view">
    <h3>{% trans "Statistieken voor gemeente" %} {{object.name}}</h3>

    <div class="mb-3">
    {% if not only_test_sessions and request.user.can_export_dialogs %}
        Exporteer van <input id="export-from" type="date"/>
        tot
        <input id="export-to" type="date"/>
        <a class="btn btn-primary" id="export-dialogs" data-url="{% url "statistics:statistics_export" gemeente_slug=current_gemeente.slug %}">Exporteer statistieken</a>
    {% endif %}
    </div>

    <div class="row mb-4 config-tiles">
        {% if "utters.statistics_read" in perms %}
        {% for graph in graph_definitions %}
            <div class="col-sm-6 col-md-2">
                <a href="{% url 'statistics:dynamic_statistics' gemeente_slug=object.slug graph_slug=graph.slug %}" class="unvisited">
                    <div class="dashboard-tile card-short text-white bg-stats">
                        <div class="card-body">
                            <div class="h1 text-muted text-right mb-4">
                                <i class="cui-list"></i>
                            </div>
                            <small class="text text-uppercase font-weight-bold">{{graph.title}}</small>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% else %}
    <div class="d-flex justify-content-center">
    {% if current_gemeente.website_image %}
        <img class="municipality-website" src="{{ settings.MEDIA_URL }}{{ current_gemeente.website_image }}">
    {% else %}
        <img class="navbar-brand-full" height="350" {% if current_gemeente.municipality_logo %}src="{{ settings.MEDIA_URL }}{{current_gemeente.municipality_logo}}"{% else %}src="{% static 'img/logo.svg' %}"{% endif %}>
    {% endif %}
    </div>
{% endif %}
{% endblock %}