src/antwoorden_cms/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from ratelimit.decorators import ratelimit
from two_factor.urls import urlpatterns as tf_urls

from antwoorden_cms.revproxy.view import RevProxyView

from .accounts.admin import CustomAdminSiteOTPRequired
from .accounts.views import GitLabTokenValidView, GitLabTokenView
from .config.views import WidgetStylingView
from .registration_urls import urlpatterns as registration_urls

handler500 = "antwoorden_cms.utils.views.server_error"
admin.site.site_header = "antwoorden_cms admin"
admin.site.site_title = "antwoorden_cms admin"
admin.site.index_title = "Welcome to the antwoorden_cms admin"

admin.site.__class__ = CustomAdminSiteOTPRequired

urlpatterns = [
    path("", include(tf_urls)),
    path("gitlab-token/", GitLabTokenView.as_view(), name="gitlab_token"),
    path(
        "gitlab-token/check_valid",
        GitLabTokenValidView.as_view(),
        name="gitlab_token_check_valid",
    ),
    path(
        "password_change/",
        ratelimit(key="user", method="POST", rate="5/h", block=True)(
            auth_views.PasswordChangeView.as_view()
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path("admin/hijack/", include("hijack.urls")),
    path("admin/", admin.site.urls),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Simply show the master template.
    # path("", RedirectView.as_view(url="/api/redoc/"), name="home"),
    path("api/", include("antwoorden_cms.utters.api.urls", namespace="antwoorden_cms")),
    path("", include("antwoorden_cms.utters.urls", namespace="gemeentes")),
    path("config/", include("antwoorden_cms.config.urls", namespace="config")),
    path("overview/", include("antwoorden_cms.dialogs.urls", namespace="dialogs")),
    path(
        "statistics/", include("antwoorden_cms.statistics.urls", namespace="statistics")
    ),
    path("accounts/", include(registration_urls)),
    path("i18n/", include("django.conf.urls.i18n")),
    # For backward compatibility
    path(
        "<slug:gemeente_slug>/_styling",
        WidgetStylingView.as_view(content_type="text/css"),
        name="widget_styling",
    ),
    path(
        "services/<str:host_and_port>/",
        RevProxyView.as_view(),
        name="revproxy",
    ),
    path(
        "services/<str:host_and_port>/<path:rest>",
        RevProxyView.as_view(),
        name="revproxy",
    ),
]

# NOTE: The staticfiles_urlpatterns also discovers static files (ie. no need to run collectstatic). Both the static
# folder and the media folder are only served via Django if DEBUG = True.
urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG and apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

src/antwoorden_cms/utters/api/urls.py
from django.conf import settings
from django.urls import path, re_path

from ..apps import AppConfig
from .api import schema_view
from .views import (
    DomainMetadataView,
    OrganisationDomainViewSet,
    OrganisationStorySettingsViewSet,
    OrganisationViewSet,
    PageMetadataView,
    ScrapyWebhookView,
    UtterResponseViewSet,
)

app_name = AppConfig.__name__


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path(
        "organisations/",
        OrganisationViewSet.as_view(
            {
                "get": "list",
            },
        ),
        name="organisation_list",
    ),
    path(
        "organisations/<slug:organisation_slug>/",
        OrganisationViewSet.as_view(
            {
                "get": "retrieve",
            },
        ),
        name="organisation_detail",
    ),
    path(
        "organisations/domains/<slug:organisation_slug>/",
        OrganisationDomainViewSet.as_view(
            {
                "get": "retrieve",
            },
        ),
        name="organisation_domains",
    ),
    path(
        "<slug:gemeente>/utters/<slug:utter_name>/",
        UtterResponseViewSet.as_view({"get": "retrieve"}),
        name="utters",
    ),
    path(
        "<slug:organisation>/stories/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "get": "list",
            }
        ),
        name="story_settings_list",
    ),
    path(
        "<slug:organisation>/stories/_bulk_create_or_update/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "post": "bulk_create_or_update",
            }
        ),
        name="story_settings_bulk_endpoint",
    ),
    path(
        "<slug:organisation>/stories/<slug:story_id>/",
        OrganisationStorySettingsViewSet.as_view(
            {
                "get": "retrieve",
                "post": "create",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="story_settings",
    ),
    path(
        "page-metadata",
        PageMetadataView.as_view({"post": "create"}),
        name="page_metadata",
    ),
    path(
        "domain-metadata",
        DomainMetadataView.as_view({"get": "retrieve"}),
        name="domain_metadata",
    ),
]

if settings.ENABLE_SCRAPY_ENDPOINT:
    urlpatterns.append(
        path(
            "scrapy-webhook",
            ScrapyWebhookView.as_view(),
            name="scrapy_webhook",
        ),
    )

src/antwoorden_cms/utters/urls.py
from django.urls import path

from .apps import AppConfig
from .views import (
    DynamicHyperlinkListView,
    DynamicRequiredHyperlinkListView,
    GemeenteView,
    HomePageView,
    HyperlinkCreateView,
    HyperlinkDeleteView,
    HyperlinkDetailView,
    HyperlinkEditableListView,
    HyperlinkListView,
    HyperlinkUpdateView,
    StoriesListView,
    UtterResponseChangeListView,
    UtterResponseCreatedListView,
    UtterResponseCreateView,
    UtterResponseDeleteView,
    UtterResponseDetailView,
    UtterResponseListView,
    UtterResponseRequiredEditableListView,
    UtterResponseUpdateView,
)

app_name = AppConfig.__name__

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    # Lists of yet to be edited responses
    # path('<slug:gemeente_slug>/antwoorden/editable/', UtterResponseEditableListView.as_view(), name='antwoord_list_editable'),
    path(
        "<slug:gemeente_slug>/antwoorden/editable/required",
        UtterResponseRequiredEditableListView.as_view(),
        name="antwoord_list_editable_required",
    ),
    # Municipality specific responses
    path("<slug:gemeente_slug>/", GemeenteView.as_view(), name="gemeente_detail"),
    path(
        "<slug:gemeente_slug>/antwoorden/",
        UtterResponseListView.as_view(),
        name="antwoord_list",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/create/",
        UtterResponseCreateView.as_view(),
        name="antwoord_create",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/",
        UtterResponseDetailView.as_view(),
        name="antwoord_read",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/update",
        UtterResponseUpdateView.as_view(),
        name="antwoord_update",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/<int:antwoord_pk>/delete/",
        UtterResponseDeleteView.as_view(),
        name="antwoord_delete",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/changed",
        UtterResponseChangeListView.as_view(),
        name="antwoord_changed_overview",
    ),
    path(
        "<slug:gemeente_slug>/antwoorden/created",
        UtterResponseCreatedListView.as_view(),
        name="antwoord_created_overview",
    ),
    path(
        "<slug:gemeente_slug>/stories/<str:category>",
        StoriesListView.as_view(),
        name="stories_list",
    ),
    # Variables pages
    path(
        "<slug:gemeente_slug>/hyperlinks/",
        HyperlinkListView.as_view(),
        name="hyperlink_list",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/editable/",
        HyperlinkEditableListView.as_view(),
        name="hyperlink_list_editable",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/create",
        HyperlinkCreateView.as_view(),
        name="hyperlink_create",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/",
        HyperlinkDetailView.as_view(),
        name="hyperlink_read",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/update",
        HyperlinkUpdateView.as_view(),
        name="hyperlink_update",
    ),
    path(
        "<slug:gemeente_slug>/hyperlinks/<int:hyperlink_pk>/delete/",
        HyperlinkDeleteView.as_view(),
        name="hyperlink_delete",
    ),
    # Dynamic hyperlinks
    path(
        "<slug:gemeente_slug>/dynamic-hyperlinks/",
        DynamicHyperlinkListView.as_view(),
        name="dynamic_hyperlink_list",
    ),
    path(
        "<slug:gemeente_slug>/dynamic-required-hyperlinks/",
        DynamicRequiredHyperlinkListView.as_view(),
        name="dynamic_required_hyperlink_list",
    ),
]

src/antwoorden_cms/utters/forms.py
from copy import copy

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Gemeente, Hyperlink, SiteConfiguration, UtterResponse


class UtterResponseForm(forms.ModelForm):
    class Meta:
        model = UtterResponse
        fields = ("response",)
        labels = {"response": _("Antwoord")}

    def __init__(self, *args, **kwargs):
        self.gemeente = kwargs.pop("gemeente", "")
        self.is_staged = kwargs.pop("is_staged", "")
        super().__init__(*args, **kwargs)

        self.fields["response"].label = f"Antwoord Gem {self.gemeente}"

        # The help_text from the utter metadata will be used instead
        self.fields["response"].help_text = ""

    def clean(self):
        # Validate that utter does not exist yet for municipality
        if self.gemeente and self.initial.get("utter"):
            if UtterResponse.objects.filter(
                gemeente__name=self.gemeente,
                utter=self.initial["utter"],
                is_staged=self.is_staged,
            ).exists():
                raise ValidationError(_("Dit antwoord bestaat al voor deze gemeente"))


class HyperlinkForm(forms.ModelForm):
    class Meta:
        model = Hyperlink
        fields = (
            "name",
            "label",
            "url",
            "title",
        )
        labels = {
            "name": _("Machinenaam"),
        }

    def __init__(self, *args, **kwargs):
        required = kwargs.pop("required", [])
        self.gemeente = kwargs.pop("gemeente", "")
        self.is_staged = kwargs.pop("is_staged", "")

        super().__init__(*args, **kwargs)

        # In case of creating a custom Hyperlink (not used in default utters)
        if not self.instance.id and not self.initial.get("name"):
            return

        # Make `name` not editable when creating a predefined Hyperlink
        if self.initial.get("name"):
            self.fields["name"].disabled = True

        # Do not allow editing of name
        if self.instance.id:
            self.fields.pop("name")

        fields = copy(self.fields)

        site_config = SiteConfiguration.get_solo()

        for field in fields:
            if field == "label":
                continue

            # Only remove fields if specified in site configuration
            if field != "name" and field not in required:
                if site_config.hyperlinks_show_only_used_attributes:
                    self.fields.pop(field)
            else:
                self.fields[field].required = True

    def clean(self):
        data = self.cleaned_data

        # Validate that hyperlink does not exist yet for municipality
        if self.gemeente and not self.instance.pk:
            if Hyperlink.objects.filter(
                gemeente=self.gemeente,
                name=data.get("name", self.initial["name"]),
                is_staged=self.is_staged,
            ).exists():
                raise ValidationError(_("Deze variabele bestaat al voor deze gemeente"))


class GemeenteAdminForm(forms.ModelForm):
    class Meta:
        model = Gemeente
        fields = "__all__"
        widgets = {
            "main_widget_color": forms.widgets.TextInput(attrs={"type": "color"}),
        }


class HyperlinksImportForm(forms.Form):
    import_file = forms.FileField(
        label=_("bestand"),
        required=True,
        help_text=_("Het YAML bestand met de hyperlinks."),
    )

src/antwoorden_cms/utters/templates/utters/table/header_antwoord.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'questions' %}{{order}}{% endif %}" data-param-name="questions">
                {% if sort == 'questions' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Klantvraag/vragen" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'response' %}{{order}}{% endif %}" data-param-name="response">
                {% if sort == 'response' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Antwoord Gem" %}
            </a>
        </th>
        {% comment %} <th scope='col'>{% trans "Noodzakelijk aan te passen?" %}</th> {% endcomment %}
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/header_antwoord_changed_overview.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'questions' %}{{order}}{% endif %}" data-param-name="questions">
                {% if sort == 'questions' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Klantvraag/vragen" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'response' %}{{order}}{% endif %}" data-param-name="response">
                {% if sort == 'response' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Lokaal antwoord Gem" %}
            </a>
        </th>
        {% comment %} <th scope='col'>{% trans "Noodzakelijk aan te passen?" %}</th> {% endcomment %}
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'default_response' %}{{order}}{% endif %}" data-param-name="default_response">
                {% if sort == 'default_response' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Standaard antwoord Gem" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'modified_on' %}{{order}}{% endif %}" data-param-name="modified_on">
                {% if sort == 'modified_on' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Laatst gewijzigd" %}
            </a>
        </th>
        <th scope='col'>
            {% trans "Lokale antwoord gewijzigd" %}
        </th>
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/header_antwoord_created_overview.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'questions' %}{{order}}{% endif %}" data-param-name="questions">
                {% if sort == 'questions' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Klantvraag/vragen" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'default_response' %}{{order}}{% endif %}" data-param-name="default_response">
                {% if sort == 'default_response' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Standaard antwoord Gem" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'created' %}{{order}}{% endif %}" data-param-name="created">
                {% if sort == 'created' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Nieuw sinds" %}
            </a>
        </th>
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/header_antwoord_editable.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>{% trans "Klantvraag/vragen" %}</th>
        <th scope='col'>{% trans "Antwoord Gem" %}</th>
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/header_hyperlink.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'name' %}{{order}}{% endif %}" data-param-name="name">
                {% if sort == 'name' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Naam" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'label' %}{{order}}{% endif %}" data-param-name="label">
                {% if sort == 'label' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Zichtbare tekst (label)" %}
            </a>
        </th>
        <th scope='col'>
            <a href="#" class="sorting-link {% if sort == 'url' %}{{order}}{% endif %}" data-param-name="url">
                {% if sort == 'url' %}
                    {% if order == 'asc' %}
                        <i class="cui-sort-alpha-down"></i>
                    {% elif order == 'desc' %}
                        <i class="cui-sort-alpha-up"></i>
                    {% endif %}
                {% endif %}
                {% trans "Internetadres (url)" %}
            </a>
        </th>
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/header_hyperlink_editable.html
{% load i18n %}
{% spaceless %}
<thead class="thead-light">
    <tr>
        <th scope='col'>{% trans "Naam" %}</th>
        <th scope='col'>{% trans "Noodzakelijke attributen" %}</th>
        <th scope='col'></th>
    </tr>
</thead>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_antwoord.html
{% load i18n l10n markdownify format_response %}
{% spaceless %}
<tr class="utter-row" role="button">
    <td class="w-10">
        <ul class="utter-metadata__list">
            {% for question in metadata.questions %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>
    </td>
    <td class="w-16" data-toggle="tooltip" title="{{antwoord.utter}}">{{ antwoord.response|format_response:current_gemeente|markdownify }}</td>
    {% comment %} <td class="col-xs-1">{% if metadata.required %}{% trans "Ja" %}{% else %}{% trans "Nee" %}{% endif %}</td> {% endcomment %}
    <td class="w-8">
        {% if "utters.utter_write" in perms %}
            {% include "utters/includes/antwoord_delete.html" with gemeente=current_gemeente antwoord=antwoord only %}
            {% include "utters/includes/antwoord_update.html" with gemeente=current_gemeente antwoord=antwoord only %}
        {% endif %}
    </td>
</tr>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_antwoord_changed_overview.html
{% load i18n l10n markdownify format_response %}
{% spaceless %}
<tr class="utter-row" role="button">
    <td class="w-10">
        <ul class="utter-metadata__list">
            {% for question in data.metadata.metadata.questions %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>
    </td>
    <td class="w-16" data-toggle="tooltip" title="{{data.local_override_prod.utter}}">{{ data.local_override_prod.response|format_response:current_gemeente|markdownify }}</td>
    <td class="w-16">{{ data.local_default_prod.response|format_response:current_gemeente|markdownify }}</td>
    <td class="w-8">
        {{ data.default_modified_on|date:"d-m-Y" }}
        {% if data.local_override_prod.default_changed_after_local_changed %}
            <i
                class="utter-changed-warning cui-warning text-danger"
                data-toggle="tooltip"
                title="Let op: na het aanmaken of wijzigen van dit lokale antwoord is het landelijke standaardantwoord gewijzigd. Check of het lokale antwoord nog klopt. Je kunt 3 dingen doen:

1. Je lokale antwoord klopt nog > klik op 'Lokale variant klopt nog'
2. Je lokale antwoord moet aangepast worden > klik op 'Lokale variant aanpassen'
3. Je wilt terug naar het landelijke standaardantwoord > klik op het rode prullenbakje om je lokale variant te verwijderen"
            ></i>
        {% endif %}
    </td>
    <td class="w-8">{% include "utters/includes/auditlog.html" with utterresponse=data.local_override_prod only %}</td>
    {% comment %} <td class="col-xs-1">{% if metadata.required %}{% trans "Ja" %}{% else %}{% trans "Nee" %}{% endif %}</td> {% endcomment %}
    <td class="w-8">
        {% if "utters.utter_write" in perms %}
            {% include "utters/includes/antwoord_delete.html" with gemeente=current_gemeente antwoord=data.local_override_prod only %}
            {% include "utters/includes/antwoord_update.html" with gemeente=current_gemeente antwoord=data.local_override_prod only %}
            {% if data.local_override_prod.default_changed_after_local_changed %}
                {% include "utters/includes/antwoord_accept.html" with gemeente=current_gemeente antwoord=data.local_override_prod response=data.local_override_prod.response only %}
            {% endif %}
        {% endif %}
    </td>
</tr>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_antwoord_created_overview.html
{% load i18n l10n markdownify format_response %}
{% spaceless %}
<tr class="utter-row" role="button">
    <td class="w-10">
        <ul class="utter-metadata__list">
            {% for question in metadata.questions %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>
    </td>
    <td class="w-16">{{ default_response.response|format_response:current_gemeente|markdownify }}</td>
    <td class="w-8">{{ created|date:"d-m-Y" }}</td>
    <td class="w-8">
        {% if "utters.utter_write" in perms %}
            {% include "utters/includes/antwoord_create.html" with gemeente=current_gemeente utter_name=utter_name only %}
        {% endif %}
    </td>
</tr>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_antwoord_editable.html
{% load i18n %}
{% load l10n %}
{% load markdownify format_response %}
{% spaceless %}

<tr class="utter-row" role="button">
    {% comment %} <td>{{antwoord.utter}}</td> {% endcomment %}
    <td class="w-10">
        <ul class="utter-metadata__list">
            {% for question in metadata.questions %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>
    </td>
    <td class="w-16" data-toggle="tooltip" title="{{utter_name}}">{{ antwoord.response|format_response:current_gemeente|markdownify }}</td>
    <td class="w-8">
        {% if "utters.utter_write" in perms %}
            {% include "utters/includes/antwoord_create.html" with gemeente=current_gemeente utter_name=utter_name only %}
        {% endif %}
    </td>
</tr>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_hyperlink.html
{% load i18n %}
{% load l10n %}
{% spaceless %}
<tr class="utter-row" role="button">
    <td class="w-10">{{verbose_name}}</td>
    <td class="w-10">{{hyperlink.label}}</td>
    <td class="w-16">{{hyperlink.url}}</td>
    <td class="w-8">
        {% if "utters.hyperlink_write" in perms %}
        <a href="{% url 'gemeentes:hyperlink_delete' gemeente_slug=current_gemeente.slug hyperlink_pk=hyperlink.pk %}"
            class="btn btn-danger float-right ml-2 delete-button">
            <i class="cui-trash"></i>
        </a>
        <a href="{% url 'gemeentes:hyperlink_update' gemeente_slug=current_gemeente.slug hyperlink_pk=hyperlink.pk %}"
            class="btn btn-primary float-right ml-2">
            <i class="cui-pencil"></i> {% trans "Bewerken" %}
        </a>
        {% endif %}
    </td>
</tr>
{% endspaceless %}

src/antwoorden_cms/utters/templates/utters/table/row_hyperlink_editable.html
{% load i18n %}
{% load l10n %}
{% spaceless %}
<tr class="utter-row" role="button">
    <td class="w-16">{{verbose_name}}</td>
    <td class="w-16"></td>
    <td class="w-16">
        {% comment %} <ul class="utter-metadata__list">
            {% for attr in attrs %}
                <li>{{ attr }}</li>
            {% endfor %}
        </ul> {% endcomment %}
    </td>
    <td class="w-8">
        {% if "utters.hyperlink_write" in perms %}
        <a href="{% url 'gemeentes:hyperlink_create' gemeente_slug=current_gemeente.slug %}?name={{ name }}{% if site_config.hyperlinks_show_only_used_attributes %}{% for attr in attrs %}&required={{attr}}{% endfor %}{% endif %}"
            class="btn btn-success float-right ml-2">
            <i class="cui-library-add"></i> {% trans "Aanmaken" %}
        </a>
        {% endif %}
    </td>
</tr>
{% endspaceless %}